

services:
  redis:
    image: redis:latest
    container_name: email-verification-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: email-verification-contaianer
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    command: >
      sh -c "pip install -r requirements.txt &&
              python3 manage.py makemigrations &&
              python3 manage.py migrate &&
              python3 manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    container_name: email-verification-celery
    depends_on:
      - redis
    volumes:
      - .:/app
    command: >
      sh -c "pip install -r requirements.txt &&
              celery -A email_verification worker --loglevel=info"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0


